"""Exact zero-error decision observation synthesis by constraint generation.

The finite master is a minimum-cost hitting-set MILP.  Its constraints are
generated by a continuous LP oracle that searches for two admissible power
worlds with different thermal decisions but identical selected observations.
When the oracle finds no collision, the master lower bound and feasible plan
meet: the returned batch plan is globally minimum-cost for the registered
action library, model family, margins, and numerical tolerances.
"""

from __future__ import annotations

import math
from fractions import Fraction as _Fraction
from concurrent.futures import ProcessPoolExecutor
from concurrent.futures.process import BrokenProcessPool
from dataclasses import dataclass
from multiprocessing import get_context
import os
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

import numpy as np
from scipy.optimize import Bounds, LinearConstraint, linprog, milp

from .core import (
    CandidateSpace,
    CandidateWorldPair,
    MeasurementAction,
    ObservationPlan,
    PowerPolytope,
    QueryObservationPlan,
    QueryWorldPair,
    ThermalFamily,
    WorldPair,
)
from .solver_budget import run_highs


class UnresolvedComputation(RuntimeError):
    """A numerical or infrastructure failure that prevents any conclusion.

    Raised ONLY where a failure is observed and known to be epistemic -- a
    solver that did not converge, a numerical breakdown inside a solve, a dead
    separation worker. The public boundary then turns it into UNRESOLVED.

    Classifying at the origin rather than by exception class at the boundary is
    deliberate. An earlier revision caught `ValueError`, `RuntimeError`,
    `ArithmeticError` and `MemoryError` at the top level; peer review rejected
    that, correctly. Those classes describe Python failure mechanics, not
    epistemic meaning: numpy raises `ValueError` for shape errors, a
    `ZeroDivisionError` is usually a missing precondition, and an arbitrary
    `RuntimeError` from a future dependency is a defect. Catching them wholesale
    turns a broken build into an apparently honest "cannot certify" -- exactly
    the failure this project's fail-closed taxonomy exists to prevent.
    """


def _unresolved_solve(what: str, call, *args, **kwargs):
    """Run a solver call, translating epistemic failures at their origin.

    Numerical breakdown inside a solve genuinely means "no conclusion".
    Everything else -- including a `ValueError` from a malformed matrix, which
    is a defect in the caller, not a property of the instance -- propagates.
    """
    try:
        return call(*args, **kwargs)
    except (FloatingPointError, OverflowError, np.linalg.LinAlgError) as exc:
        raise UnresolvedComputation(f"{what}: numerical breakdown: {exc}") from exc


class ContractViolation(ValueError):
    """Registered input does not satisfy the documented contract.

    Subclasses `ValueError` so existing `pytest.raises(ValueError)` callers and
    any external handler keep working, but lets the public boundary catch ONLY
    deliberate validation failures.

    Catching bare `ValueError` there is not sufficient: `np.linalg.LinAlgError`
    is itself a `ValueError` subclass, so a raw singular-matrix failure arising
    from a defect would be absorbed into UNRESOLVED. Numerical breakdown is
    epistemic only when observed at a solver boundary, where
    `_unresolved_solve` classifies it explicitly.
    """


# Caught at the public boundary -- deliberately classified failures only.
#
# TimeoutError: a wall-clock budget expiring is EPISTEMIC -- the run could not
# reach a conclusion. Before it was caught here, the driver's SIGALRM escaped
# and `_timed_call` discarded the whole result, so a 1800s dev query threw away
# its cuts, witnesses, candidate cover and anytime bound; that is why the dev
# report's bound columns are empty despite the bounds being computed.
#
# Catching the builtin globally does sit awkwardly with this file's own
# classify-at-origin rule: a dependency, socket or future defect can raise the
# same class. It is accepted deliberately and narrowly. The driver is the only
# component that installs a SIGALRM around this call, the budget is the only
# timeout in the registered pipeline, and the alternative -- letting it escape
# -- destroys the evidence an anytime method exists to produce. A dedicated
# BudgetExhausted type would be cleaner but must be raised by the driver, which
# is outside this module; recorded in ccfa.yaml rather than silently accepted.
_UNRESOLVED_FAILURES: Tuple[type, ...] = (
    ContractViolation,
    UnresolvedComputation,
    TimeoutError,
)


@dataclass(frozen=True)
class _Master:
    selected: Tuple[int, ...]
    cost: float
    lower_bound: float
    relaxation_bound: float
    dual_prices: np.ndarray
    # Where lower_bound came from, so a certificate's trust basis is visible
    # rather than implicit. "weak_duality" is verifiable from the returned
    # numbers alone; "solver_branch_and_bound" is asserted by HiGHS and is only
    # cross-checked for consistency, not proved.
    bound_provenance: str = "weak_duality"


@dataclass(frozen=True)
class _CollisionProblem:
    n: int
    objective: np.ndarray
    common_a_ub: np.ndarray
    common_b_ub: np.ndarray
    a_eq: np.ndarray
    b_eq: np.ndarray
    bounds: Tuple[Tuple[float, float], ...]
    response: np.ndarray
    ambient: np.ndarray
    error_k: np.ndarray
    limit_k: float
    margin_k: float
    feasibility_tolerance: float
    model_ids: Tuple[str, ...]


_WORKER_COLLISION_PROBLEM: Optional[_CollisionProblem] = None


def _initialize_collision_worker(problem: _CollisionProblem) -> None:
    global _WORKER_COLLISION_PROBLEM
    _WORKER_COLLISION_PROBLEM = problem


def _solve_collision_spec(
    problem: _CollisionProblem, spec: Tuple[int, int]
) -> Optional[WorldPair]:
    reject_model, point = spec
    reject_row = np.concatenate(
        (np.zeros(problem.n), -problem.response[reject_model, point])
    )
    reject_rhs = -(
        problem.limit_k
        + problem.margin_k
        - problem.error_k[reject_model]
        - problem.ambient[reject_model, point]
    )
    result = _unresolved_solve(
        "collision LP",
        run_highs,
        linprog,
        problem.objective,
        A_ub=np.vstack((problem.common_a_ub, reject_row)),
        b_ub=np.append(problem.common_b_ub, reject_rhs),
        A_eq=problem.a_eq,
        b_eq=problem.b_eq,
        bounds=problem.bounds,
        method="highs",
        label="collision LP",
        options={
            "primal_feasibility_tolerance": problem.feasibility_tolerance,
            "dual_feasibility_tolerance": problem.feasibility_tolerance,
        },
    )
    if result.status == 0:
        return WorldPair(
            safe_power_w=result.x[: problem.n].copy(),
            unsafe_power_w=result.x[problem.n :].copy(),
            safe_model_id="ROBUST_ENVELOPE",
            unsafe_model_id=problem.model_ids[reject_model],
            unsafe_point=point,
        )
    if result.status != 2:
        raise UnresolvedComputation(f"collision LP unresolved: {result.message}")
    return None


def _solve_collision_worker(spec: Tuple[int, int]) -> Optional[WorldPair]:
    if _WORKER_COLLISION_PROBLEM is None:
        raise UnresolvedComputation("collision worker was not initialized")
    return _solve_collision_spec(_WORKER_COLLISION_PROBLEM, spec)


def _configured_workers(workers: Optional[int] = None) -> int:
    value = workers
    if value is None:
        # Sequential by DEFAULT. Two independent measurements agree:
        #
        # 1. The pool is a 32x PESSIMIZATION at this instance size. A fresh
        #    spawn-context pool is built per iteration to dispatch twelve LPs of
        #    ~5-6 ms each: 0.064 s/iteration sequential against 2.07 s/iteration
        #    with eight workers, so over 96% of parallel wall time is not useful
        #    work. Even zero-overhead 8-way parallelism could save only ~53 ms
        #    per round here.
        # 2. It DEADLOCKS under a short budget. The Anytime-DSOS controller's
        #    SIGALRM can fire while the pool is spawning, leaving
        #    FileNotFoundError from SemLock._rebuild and a hung run. The 1800s
        #    dev run never hit this because the alarm never landed mid-spawn;
        #    the schema rehearsal at 25s hit it immediately.
        #
        # Set CERTITHERM_LP_WORKERS explicitly to opt back in for an instance
        # large enough that the LPs dominate process startup.
        value = int(os.environ.get("CERTITHERM_LP_WORKERS", "1"))
    if value <= 0:
        raise ContractViolation("LP separation workers must be positive")
    return value


def _pair_rows(polytope: PowerPolytope) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    n = polytope.dimension
    zeros_eq = np.zeros((polytope.a_eq.shape[0], n))
    a_eq = np.vstack(
        (np.hstack((polytope.a_eq, zeros_eq)), np.hstack((zeros_eq, polytope.a_eq)))
    )
    b_eq = np.concatenate((polytope.b_eq, polytope.b_eq))
    zeros_ub = np.zeros((polytope.a_ub.shape[0], n))
    a_ub = np.vstack(
        (np.hstack((polytope.a_ub, zeros_ub)), np.hstack((zeros_ub, polytope.a_ub)))
    )
    b_ub = np.concatenate((polytope.b_ub, polytope.b_ub))
    return a_eq, b_eq, a_ub, b_ub


def _robust_safe_rows(
    thermal: ThermalFamily, margin_k: float
) -> Tuple[np.ndarray, np.ndarray]:
    """All model/point upper bounds defining one fail-closed SAFE cell."""

    rows = thermal.response_k_per_w.reshape(-1, thermal.blocks)
    rhs = (
        thermal.limit_k
        - margin_k
        - thermal.error_k[:, None]
        - thermal.ambient_k
    ).reshape(-1)
    return rows, rhs


def _collision_search(
    polytope: PowerPolytope,
    thermal: ThermalFamily,
    actions: Sequence[MeasurementAction],
    selected: Iterable[int],
    margin_k: float,
    feasibility_tolerance: float,
    workers: Optional[int],
    exhaustive: bool,
) -> Tuple[WorldPair, ...]:
    """Separate safe/reject cells with deterministic parallel LP batches."""

    n = polytope.dimension
    a_eq, b_eq, base_a_ub, base_b_ub = _pair_rows(polytope)
    action_rows: List[np.ndarray] = []
    action_rhs: List[float] = []
    for index in selected:
        action = actions[index]
        delta = np.concatenate((action.vector, -action.vector))
        action_rows.extend((delta, -delta))
        action_rhs.extend((action.tolerance, action.tolerance))

    bounds = tuple(zip(polytope.lower_w, polytope.upper_w)) * 2
    response = thermal.response_k_per_w
    ambient = thermal.ambient_k
    robust_rows, robust_rhs = _robust_safe_rows(thermal, margin_k)
    safe_rows = np.hstack((robust_rows, np.zeros_like(robust_rows)))
    common_chunks = [base_a_ub, safe_rows]
    common_rhs_chunks = [base_b_ub, robust_rhs]
    if action_rows:
        common_chunks.append(np.asarray(action_rows))
        common_rhs_chunks.append(np.asarray(action_rhs))
    common_a_ub = np.vstack(common_chunks)
    common_b_ub = np.concatenate(common_rhs_chunks)
    specs = tuple(
        (reject_model, point)
        for reject_model in range(response.shape[0])
        for point in range(response.shape[1])
    )
    if not specs:
        # ThermalFamily validation rejects an empty model/point grid, so this
        # is unreachable today. Guard it anyway: an empty spec list would make
        # "no collision found" vacuously true and silently certify anything.
        raise UnresolvedComputation("no reject cells to separate")
    worker_count = min(_configured_workers(workers), len(specs))
    problem = _CollisionProblem(
        n=n,
        objective=np.zeros(2 * n),
        common_a_ub=common_a_ub,
        common_b_ub=common_b_ub,
        a_eq=a_eq,
        b_eq=b_eq,
        bounds=bounds,
        response=response,
        ambient=ambient,
        error_k=thermal.error_k,
        limit_k=thermal.limit_k,
        margin_k=margin_k,
        feasibility_tolerance=feasibility_tolerance,
        model_ids=thermal.model_ids,
    )

    if worker_count == 1:
        collisions = []
        evaluated = 0
        for spec in specs:
            collision = _solve_collision_spec(problem, spec)
            evaluated += 1
            if collision is not None:
                collisions.append(collision)
                if not exhaustive:
                    break
        if exhaustive and evaluated != len(specs):
            raise UnresolvedComputation(
                f"exhaustive separation evaluated {evaluated}/{len(specs)} "
                "reject cells"
            )
        return tuple(collisions)

    collisions: List[WorldPair] = []
    # Most approximate-policy calls collide in the first reject cell. Probe
    # only that cell before paying process-startup cost; a negative probe then
    # triggers the exhaustive parallel batches needed for a sound certificate.
    probe_count = 0 if exhaustive else min(1, len(specs))
    for spec in specs[:probe_count]:
        collision = _solve_collision_spec(problem, spec)
        if collision is not None:
            return (collision,)
    remaining = specs[probe_count:]
    if not remaining:
        return ()
    with ProcessPoolExecutor(
        max_workers=worker_count,
        mp_context=get_context("spawn"),
        initializer=_initialize_collision_worker,
        initargs=(problem,),
    ) as pool:
        if exhaustive:
            results = tuple(pool.map(_solve_collision_worker, remaining))
            if len(results) != len(remaining):
                # An empty or short result set would otherwise be
                # indistinguishable from "searched everything, found nothing"
                # -- and that indistinguishability is what a certificate would
                # rest on. Fail closed instead.
                raise UnresolvedComputation(
                    f"exhaustive separation returned {len(results)}/"
                    f"{len(remaining)} reject-cell results"
                )
            return tuple(c for c in results if c is not None)
        for start in range(0, len(remaining), worker_count):
            batch = tuple(
                pool.map(
                    _solve_collision_worker,
                    remaining[start : start + worker_count],
                )
            )
            collision = next((item for item in batch if item is not None), None)
            if collision is not None:
                collisions.append(collision)
                break
    return tuple(collisions)


def _collision(
    polytope: PowerPolytope,
    thermal: ThermalFamily,
    actions: Sequence[MeasurementAction],
    selected: Iterable[int],
    margin_k: float,
    feasibility_tolerance: float,
    workers: Optional[int] = None,
) -> Optional[WorldPair]:
    """Return the first collision; certify absence by parallel exhaustive scan."""

    collisions = _collision_search(
        polytope,
        thermal,
        actions,
        selected,
        margin_k,
        feasibility_tolerance,
        workers,
        False,
    )
    return collisions[0] if collisions else None


def _collisions(
    polytope: PowerPolytope,
    thermal: ThermalFamily,
    actions: Sequence[MeasurementAction],
    selected: Iterable[int],
    margin_k: float,
    feasibility_tolerance: float,
    workers: Optional[int] = None,
) -> Tuple[WorldPair, ...]:
    """Return one collision per reachable reject cell in deterministic order."""

    try:
        return _collision_search(
            polytope,
            thermal,
            actions,
            selected,
            margin_k,
            feasibility_tolerance,
            workers,
            True,
        )
    except BrokenProcessPool as exc:
        # A separation worker died. The batch as a whole cannot support any
        # conclusion -- results from completed futures are discarded rather
        # than committed, so no partially-consumed batch can leak into the
        # cut set. Epistemic, not a defect.
        raise UnresolvedComputation(f"separation worker pool broke: {exc}") from exc


def _state_specs(thermal: ThermalFamily, state: str) -> Iterable[Tuple[int, int]]:
    if state == "ANY":
        return ((-1, -1),)
    if state == "SAFE":
        return ((-1, -1),)
    if state == "REJECT":
        return (
            (model, point)
            for model in range(len(thermal.model_ids))
            for point in range(thermal.response_k_per_w.shape[1])
        )
    raise ValueError(f"unknown decision state {state}")


def _state_constraints(
    thermal: ThermalFamily,
    state: str,
    model: int,
    point: int,
    side: int,
    margin_k: float,
) -> Tuple[np.ndarray, np.ndarray]:
    n = thermal.blocks
    if state == "ANY":
        return np.empty((0, 2 * n)), np.empty(0)
    if state == "SAFE":
        rows, rhs = _robust_safe_rows(thermal, margin_k)
    else:
        response = thermal.response_k_per_w[model]
        rows = -response[point][None, :]
        rhs = np.array(
            [
                -(
                    thermal.limit_k
                    + margin_k
                    - thermal.error_k[model]
                    - thermal.ambient_k[model, point]
                )
            ]
        )
    pad = np.zeros_like(rows)
    return (np.hstack((rows, pad)) if side == 0 else np.hstack((pad, rows))), rhs


def _single_state_world(
    candidate: CandidateSpace,
    state: str,
    margin_k: float,
    feasibility_tolerance: float,
) -> Optional[Tuple[np.ndarray, str]]:
    """Find one world in a state; used to couple equal-state query sides."""

    power, thermal = candidate.power, candidate.thermal
    for model, point in _state_specs(thermal, state):
        if state == "ANY":
            rows, rhs, model_id = power.a_ub, power.b_ub, "UNCONSTRAINED"
        elif state == "SAFE":
            safe_rows, safe_rhs = _robust_safe_rows(thermal, margin_k)
            rows = np.vstack((power.a_ub, safe_rows))
            rhs = np.concatenate(
                (
                    power.b_ub,
                    safe_rhs,
                )
            )
            model_id = "ROBUST_ENVELOPE"
        else:
            rows = np.vstack(
                (power.a_ub, -thermal.response_k_per_w[model, point][None, :])
            )
            rhs = np.concatenate(
                (
                    power.b_ub,
                    np.array(
                        [
                            -(
                                thermal.limit_k
                                + margin_k
                                - thermal.error_k[model]
                                - thermal.ambient_k[model, point]
                            )
                        ]
                    ),
                )
            )
            model_id = thermal.model_ids[model]
        result = run_highs(
            linprog,
            np.zeros(power.dimension),
            A_ub=rows,
            b_ub=rhs,
            A_eq=power.a_eq,
            b_eq=power.b_eq,
            bounds=list(zip(power.lower_w, power.upper_w)),
            method="highs",
            label="state feasibility LP",
            options={
                "primal_feasibility_tolerance": feasibility_tolerance,
                "dual_feasibility_tolerance": feasibility_tolerance,
            },
        )
        if result.status == 0:
            return result.x.copy(), model_id
        if result.status != 2:
            raise UnresolvedComputation(
                f"state feasibility LP unresolved: {result.message}"
            )
    return None


def _state_model_id(thermal: ThermalFamily, state: str, model: int) -> str:
    if state == "SAFE":
        return "ROBUST_ENVELOPE"
    if state == "ANY":
        return "UNCONSTRAINED"
    return thermal.model_ids[model]


def _state_collision(
    candidate: CandidateSpace,
    actions: Sequence[MeasurementAction],
    selected: Iterable[int],
    left_state: str,
    right_state: str,
    margin_k: float,
    feasibility_tolerance: float,
) -> Optional[CandidateWorldPair]:
    polytope, thermal = candidate.power, candidate.thermal
    if left_state == right_state:
        world = _single_state_world(
            candidate, left_state, margin_k, feasibility_tolerance
        )
        if world is None:
            return None
        power, model_id = world
        return CandidateWorldPair(
            candidate_id=candidate.candidate_id,
            left_power_w=power,
            right_power_w=power.copy(),
            left_state=left_state,
            right_state=right_state,
            left_model_id=model_id,
            right_model_id=model_id,
        )
    n = polytope.dimension
    a_eq, b_eq, base_a_ub, base_b_ub = _pair_rows(polytope)
    action_rows, action_rhs = [], []
    for index in selected:
        action = actions[index]
        delta = np.concatenate((action.vector, -action.vector))
        action_rows.extend((delta, -delta))
        action_rhs.extend((action.tolerance, action.tolerance))
    bounds = list(zip(polytope.lower_w, polytope.upper_w)) * 2
    for left_model, left_point in _state_specs(thermal, left_state):
        left_rows, left_rhs = _state_constraints(
            thermal, left_state, left_model, left_point, 0, margin_k
        )
        for right_model, right_point in _state_specs(thermal, right_state):
            right_rows, right_rhs = _state_constraints(
                thermal, right_state, right_model, right_point, 1, margin_k
            )
            chunks = [base_a_ub, left_rows, right_rows]
            rhs_chunks = [base_b_ub, left_rhs, right_rhs]
            if action_rows:
                chunks.append(np.asarray(action_rows))
                rhs_chunks.append(np.asarray(action_rhs))
            result = run_highs(
                linprog,
                np.zeros(2 * n),
                A_ub=np.vstack(chunks),
                b_ub=np.concatenate(rhs_chunks),
                A_eq=a_eq,
                b_eq=b_eq,
                bounds=bounds,
                method="highs",
                label="query collision LP",
                options={
                    "primal_feasibility_tolerance": feasibility_tolerance,
                    "dual_feasibility_tolerance": feasibility_tolerance,
                },
            )
            if result.status == 0:
                return CandidateWorldPair(
                    candidate_id=candidate.candidate_id,
                    left_power_w=result.x[:n].copy(),
                    right_power_w=result.x[n:].copy(),
                    left_state=left_state,
                    right_state=right_state,
                    left_model_id=_state_model_id(
                        thermal, left_state, left_model
                    ),
                    right_model_id=_state_model_id(
                        thermal, right_state, right_model
                    ),
                )
            if result.status != 2:
                raise UnresolvedComputation(
                    f"query collision LP unresolved: {result.message}"
                )
    return None


def _decision_states(candidate_count: int, decision: int) -> Tuple[str, ...]:
    if decision == candidate_count:
        return ("REJECT",) * candidate_count
    return tuple(
        "REJECT" if index < decision else "SAFE" if index == decision else "ANY"
        for index in range(candidate_count)
    )


def _required_candidate_indices(
    candidates: Sequence[CandidateSpace],
    margin_k: float,
    feasibility_tolerance: float,
) -> Tuple[int, ...]:
    """Candidates whose SAFE/REJECT ambiguity changes a reachable decision."""

    state_exists = {
        (index, state): _single_state_world(
            candidate, state, margin_k, feasibility_tolerance
        )
        is not None
        for index, candidate in enumerate(candidates)
        for state in ("ANY", "SAFE", "REJECT")
    }
    reachable = tuple(
        decision
        for decision in range(len(candidates) + 1)
        if all(
            state_exists[index, state]
            for index, state in enumerate(
                _decision_states(len(candidates), decision)
            )
        )
    )
    return tuple(
        decision
        for decision in reachable[:-1]
        if decision < len(candidates)
    )


def _query_collision(
    candidates: Sequence[CandidateSpace],
    actions: Sequence[MeasurementAction],
    selected: Iterable[int],
    margin_k: float,
    feasibility_tolerance: float,
    cache: Optional[
        Dict[Tuple[int, Tuple[int, ...], str, str], Optional[CandidateWorldPair]]
    ] = None,
) -> Optional[QueryWorldPair]:
    selected_set = set(selected)
    action_index = {
        candidate.candidate_id: [
            index for index, action in enumerate(actions) if action.candidate_id == candidate.candidate_id
        ]
        for candidate in candidates
    }
    for left_decision in range(len(candidates) + 1):
        left_states = _decision_states(len(candidates), left_decision)
        for right_decision in range(left_decision + 1, len(candidates) + 1):
            right_states = _decision_states(len(candidates), right_decision)
            pairs = []
            for candidate_index, (candidate, left_state, right_state) in enumerate(
                zip(candidates, left_states, right_states)
            ):
                global_indices = action_index[candidate.candidate_id]
                local_actions = [actions[index] for index in global_indices]
                local_selected = [
                    local for local, index in enumerate(global_indices) if index in selected_set
                ]
                key = (
                    candidate_index,
                    tuple(local_selected),
                    left_state,
                    right_state,
                )
                if cache is not None and key in cache:
                    pair = cache[key]
                else:
                    pair = _state_collision(
                        candidate,
                        local_actions,
                        local_selected,
                        left_state,
                        right_state,
                        margin_k,
                        feasibility_tolerance,
                    )
                    if cache is not None:
                        cache[key] = pair
                if pair is None:
                    break
                pairs.append(pair)
            if len(pairs) == len(candidates):
                name = lambda value: (
                    candidates[value].candidate_id
                    if value < len(candidates)
                    else "NO_FEASIBLE_CANDIDATE"
                )
                return QueryWorldPair(
                    left_decision=name(left_decision),
                    right_decision=name(right_decision),
                    candidates=tuple(pairs),
                )
    return None


def _undominated_columns(
    costs: np.ndarray, cover: np.ndarray
) -> Tuple[np.ndarray, np.ndarray]:
    """Remove hitting-set columns dominated in coverage and cost.

    Column ``right`` dominates ``left`` when it covers every cut covered by
    ``left`` at no greater cost.  Replacing ``left`` by ``right`` preserves
    both integer and fractional feasibility, so this reduction preserves the
    MILP optimum and its LP lower bound.
    """

    column_masks = []
    for column in range(cover.shape[1]):
        mask = 0
        for row in np.flatnonzero(cover[:, column]):
            mask |= 1 << int(row)
        column_masks.append(mask)
    keep = []
    for left, (left_cost, left_mask) in enumerate(zip(costs, column_masks)):
        if left_mask == 0:
            continue
        dominated = False
        for right, (right_cost, right_mask) in enumerate(zip(costs, column_masks)):
            if left == right or right_cost > left_cost:
                continue
            if left_mask & right_mask != left_mask:
                continue
            if right_cost < left_cost or right_mask != left_mask or right < left:
                dominated = True
                break
        if not dominated:
            keep.append(left)
    indices = np.asarray(keep, dtype=int)
    return indices, cover[:, indices]


def _solve_master(
    costs: np.ndarray,
    cuts: Sequence[np.ndarray],
    incumbent: Optional[Sequence[int]] = None,
) -> _Master:
    if not cuts:
        return _Master((), 0.0, 0.0, 0.0, np.empty(0))
    cover = np.asarray(cuts, dtype=float)
    columns, reduced_cover = _undominated_columns(costs, cover)
    reduced_costs = costs[columns]
    relaxed = run_highs(
        linprog,
        reduced_costs,
        A_ub=-reduced_cover,
        b_ub=-np.ones(len(cuts)),
        bounds=[(0.0, 1.0)] * reduced_costs.size,
        method="highs",
        label="observation-master LP relaxation",
    )
    if not relaxed.success:
        raise UnresolvedComputation("observation master did not solve to optimality")
    dual = -np.asarray(relaxed.ineqlin.marginals)
    exact_dual = _integer_lagrangian_bound(costs, cuts, dual)
    certified_relaxation = (
        _fraction_lower_float(exact_dual) if exact_dual is not None else None
    )
    certified_relaxation = max(certified_relaxation or 0.0, 0.0)

    rounded = np.rint(relaxed.x)
    if (
        np.max(np.abs(relaxed.x - rounded)) <= 1e-8
        and np.all(reduced_cover @ rounded >= 1.0 - 1e-8)
    ):
        selected = tuple(columns[np.flatnonzero(rounded > 0.5)].tolist())
        exact_cost = float(np.sum(costs[list(selected)]))
        certified_cost = _self_verified_master_cost(
            costs,
            exact_dual,
            selected,
        )
        if certified_cost is not None:
            # Self-verifiable without the MIP solver: the code above has
            # checked that the rounded solution covers every cut and that the
            # exact weak-duality bound, after valid lattice lifting, equals its
            # exact registered cost. No solver objective is trusted here.
            return _Master(
                selected,
                exact_cost,
                certified_cost,
                certified_relaxation,
                dual,
                "weak_duality",
            )

    if incumbent is not None:
        selected = tuple(sorted(int(index) for index in incumbent))
        incumbent_vector = np.zeros(costs.size)
        incumbent_vector[list(selected)] = 1.0
        incumbent_cost = float(costs @ incumbent_vector)
        certified_cost = _self_verified_master_cost(
            costs,
            exact_dual,
            selected,
        )
        if (
            np.all(cover @ incumbent_vector >= 1.0 - 1e-8)
            and certified_cost is not None
        ):
            return _Master(
                selected,
                incumbent_cost,
                certified_cost,
                certified_relaxation,
                dual,
                "weak_duality",
            )

    constraint = LinearConstraint(
        reduced_cover, np.ones(len(cuts)), np.full(len(cuts), np.inf)
    )
    integer = run_highs(
        milp,
        c=reduced_costs,
        integrality=np.ones(reduced_costs.size),
        bounds=Bounds(np.zeros(reduced_costs.size), np.ones(reduced_costs.size)),
        constraints=constraint,
        label="observation-master MILP",
        options={"mip_rel_gap": 0.0},
    )
    if not integer.success:
        raise UnresolvedComputation("observation master did not solve to optimality")
    selected = tuple(columns[np.flatnonzero(integer.x > 0.5)].tolist())

    # Verify the solver's answer instead of trusting it. `OPTIMAL` is issued
    # when this cost meets this bound, so an unverified solver result is a
    # direct route to a false certificate. Each check below is cheap relative
    # to the solve that produced it.
    plan = np.zeros(costs.size)
    if selected:
        plan[list(selected)] = 1.0
    if not np.all(cover @ plan >= 1.0 - 1e-8):
        # The returned selection must actually hit every accumulated cut.
        raise UnresolvedComputation(
            "observation master returned a selection that does not cover "
            "every discovered cut"
        )
    exact_cost = float(costs @ plan)
    integer_objective = float(integer.fun)
    if not np.isfinite(integer_objective):
        raise UnresolvedComputation("observation master returned a non-finite objective")
    if abs(exact_cost - integer_objective) > 1e-6 * max(1.0, abs(exact_cost)):
        # A reported objective that disagrees with the cost of the reported
        # selection means one of the two is not what it claims to be.
        raise UnresolvedComputation(
            f"observation master objective {integer.fun} disagrees with the "
            f"cost {exact_cost} of its own selection"
        )

    lower_bound = float(getattr(integer, "mip_dual_bound", integer.fun))
    slack = 1e-6 * max(1.0, abs(exact_cost))
    if not np.isfinite(lower_bound):
        raise UnresolvedComputation("observation master returned a non-finite dual bound")

    # Cross-check against a bound this module can certify itself. The weak-duality
    # bound is valid regardless of solver accuracy, so a claimed MILP bound below
    # it is provably wrong and is rejected.
    if lower_bound < certified_relaxation - slack:
        raise UnresolvedComputation(
            f"observation master dual bound {lower_bound} lies below the "
            f"independently certified bound {certified_relaxation}"
        )
    if lower_bound > exact_cost + slack:
        raise UnresolvedComputation(
            f"observation master dual bound {lower_bound} exceeds its own "
            f"integer cost {exact_cost}"
        )

    # KNOWN RESIDUAL, do not overstate this function's guarantees.
    # These checks make an INCONSISTENT solver answer detectable; they do NOT
    # make integer optimality solver-independent. A self-consistent wrong
    # answer still passes: with true optimum 2 and LP relaxation 1.5, a solver
    # returning a feasible plan of cost 3 with mip_dual_bound 3 satisfies
    # coverage, objective agreement, and both bound comparisons, and
    # cost == bound would then yield OPTIMAL at a suboptimal plan.
    # Closing this needs either a certified branch-and-bound proof object
    # (SciPy/HiGHS does not expose one) or exhaustive enumeration. Until then
    # OPTIMAL's integer-optimality claim rests on trusting HiGHS whenever the
    # LP relaxation is not tight. Recorded in ccfa.yaml open_risks.
    # If the certified bound already meets the integer cost, this certificate is
    # self-contained: the numbers alone prove optimality and HiGHS's branch and
    # bound is not being relied on. Otherwise the gap is closed only by the
    # solver's asserted dual bound, and the result says so.
    provenance = "solver_branch_and_bound"
    certified_cost = _self_verified_master_cost(costs, exact_dual, selected)
    if certified_cost is not None:
        lower_bound = certified_cost
        provenance = "weak_duality"
    elif lower_bound < exact_cost - slack:
        raise UnresolvedComputation(
            "observation master did not close its integer optimality gap"
        )
    return _Master(
        selected,
        exact_cost,
        lower_bound,
        certified_relaxation,
        dual,
        provenance,
    )


def _cost_lattice(costs: np.ndarray) -> Optional[_Fraction]:
    """Largest g such that every action cost is an integer multiple of g.

    Every contract cost is then a multiple of g, so a fractional lower bound L
    can be rounded UP to the next lattice point without losing validity. With
    the registered costs 1/2/4/8 this is 1.
    """
    # EXACT conversion, no limit_denominator. A float IS an exact dyadic
    # rational, so Fraction(float) is lossless. Approximating here was unsound:
    # with a 1e-12 relative tolerance, costs like 1.0000000000005 reconstruct as
    # Fraction(1) and the function would return g=1 although that cost is not a
    # multiple of 1 -- the lifted bound would then be invalid and could certify
    # a suboptimal plan. Approximating the DUAL is safe (any y>=0 works);
    # approximating COSTS is not, because it changes the problem being bounded.
    # If the exact lattice is very fine the lifting simply does nothing, which
    # is the safe failure direction.
    fractions = []
    for value in costs:
        if not np.isfinite(value):
            return None
        fractions.append(_Fraction(float(value)))
    if not fractions:
        return None
    g = fractions[0]
    for frac in fractions[1:]:
        # gcd over rationals: gcd(num)/lcm(den)
        numerator_gcd = math.gcd(g.numerator, frac.numerator)
        denominator_gcd = math.gcd(g.denominator, frac.denominator)
        g = _Fraction(
            numerator_gcd,
            g.denominator * frac.denominator // denominator_gcd,
        )
    return g if g > 0 else None


def _fraction_lower_float(value: _Fraction) -> Optional[float]:
    """Convert an exact lower bound without ever rounding it upward."""

    try:
        rounded = float(value)
    except OverflowError:
        return None
    if not np.isfinite(rounded):
        return None
    if _Fraction(rounded) > value:
        rounded = float(np.nextafter(rounded, -np.inf))
    return rounded


def _self_verified_master_cost(
    costs: np.ndarray,
    exact_dual: Optional[_Fraction],
    selected: Sequence[int],
) -> Optional[float]:
    """Return the selected cost only when weak duality proves it optimal."""

    lattice = _cost_lattice(costs)
    if exact_dual is None or lattice is None:
        return None
    lifted = _Fraction(math.ceil(exact_dual / lattice)) * lattice
    selected_cost = sum(
        (_Fraction(float(costs[index])) for index in selected),
        _Fraction(0),
    )
    if lifted != selected_cost:
        return None
    return _fraction_lower_float(lifted)


def _integer_lagrangian_bound(
    costs: np.ndarray, cuts: Sequence[np.ndarray], dual: np.ndarray
) -> Optional[_Fraction]:
    """Exact-arithmetic evaluation of L(y) = 1'y + sum_j min(0, c_j - (C'y)_j).

    Valid for ANY y >= 0 -- dual feasibility is not required -- so the solver's
    dual vector is only a guess and cannot make the bound wrong. Evaluating in
    Fractions rather than floats removes the need for the defensive deflation
    that a float evaluation required, which is what previously left a spurious
    ~1e-9 gap on instances whose true gap is zero.

    Returns an exact rational, or None if the inputs are not representable.
    """
    try:
        # y may be approximated: the bound is valid for ANY y >= 0, so a
        # rounded dual only loosens it. Costs may NOT be approximated -- that
        # would bound a different problem than the one being certified.
        y = [_Fraction(float(v)).limit_denominator(10**9) for v in dual]
        c = [_Fraction(float(v)) for v in costs]
    except (ValueError, OverflowError):
        return None
    cover_check = np.asarray(cuts, dtype=float)
    if not np.all((cover_check == 0.0) | (cover_check == 1.0)):
        # The membership test below assumes 0/1 cuts. They are built that way,
        # but a non-binary coefficient would silently corrupt the bound.
        return None
    if any(v < 0 for v in y):
        y = [v if v > 0 else _Fraction(0) for v in y]
    cover = np.asarray(cuts, dtype=float)
    total = sum(y)
    for j in range(len(c)):
        col = cover[:, j]
        loading = sum(y[i] for i in range(len(y)) if col[i] > 0.5)
        residual = c[j] - loading
        if residual < 0:
            total += residual
    return total


def _anytime_lower_bound(
    costs: np.ndarray, cuts: Sequence[np.ndarray]
) -> Optional[float]:
    """Certified lower bound on the minimum-cost plan, from the cuts so far.

    Valid GLOBALLY, not merely for the restricted master: every discovered cut
    is a necessary condition for every feasible plan, so omitting the
    undiscovered ones only enlarges the feasible set and the optimum over a
    subset cannot exceed the true optimum. (If the instance is
    UNSYNTHESIZABLE the true optimum is +inf and any finite bound stays valid,
    merely uninformative.) Relaxing integrality lowers it further.

    NOT simply `linprog(...).fun`. That is a floating-point PRIMAL objective;
    solver tolerance can put it slightly ABOVE the exact LP optimum, which
    would make it an invalid lower bound in exactly the regime where the bound
    matters. Instead the solver's dual prices are used only as a *guess*, and
    the returned number is computed here by weak duality:

        L(y) = 1'y + sum_a min(0, c_a - (C'y)_a),   y >= 0

    which lower-bounds the optimum for ANY nonnegative y, however inaccurate.
    Solver error can therefore only make the bound loose, never wrong. The
    bound is evaluated in exact rational arithmetic over the registered float
    inputs, then converted to float with directed downward rounding.

    Monotone in principle as cuts accumulate; the caller keeps the maximum, so
    a loose y on one call cannot lower an already-established bound.

    Returns None when no bound can be justified. A bound is never fabricated.
    """

    costs = np.asarray(costs, dtype=float)
    if costs.size == 0 or not np.all(np.isfinite(costs)):
        return None
    if np.any(costs < 0):
        # The empty-cut bound of 0.0 and the min(0, .) term below both assume
        # nonnegative costs. MeasurementAction enforces cost > 0, so this is a
        # guard against a future caller, not a reachable state.
        return None
    if not cuts:
        return 0.0

    cover = np.asarray(cuts, dtype=float)
    if cover.ndim != 2 or cover.shape[1] != costs.size:
        # A ragged or mis-dimensioned cut set breaks the correspondence
        # between cut columns and action costs, which is what the global-bound
        # argument rests on.
        return None

    try:
        relaxed = run_highs(
            linprog,
            costs,
            A_ub=-cover,
            b_ub=-np.ones(cover.shape[0]),
            bounds=[(0.0, 1.0)] * costs.size,
            method="highs",
            label="anytime lower-bound LP",
        )
    except (ValueError, TypeError):
        return None
    if not relaxed.success or relaxed.ineqlin is None:
        return None

    # linprog was given -cover x <= -1, so its marginals are <= 0 for an active
    # >= constraint; negate to obtain the y >= 0 of the form above.
    dual = np.maximum(-np.asarray(relaxed.ineqlin.marginals, dtype=float), 0.0)
    if not np.all(np.isfinite(dual)):
        return None
    # EXACT evaluation. The float path this replaces used a 1e-9 relative
    # deflation to absorb rounding error, which is a heuristic rather than a
    # proved bound and degrades as cut and action counts grow -- exactly the
    # regime this project runs in. `_integer_lagrangian_bound` evaluates the
    # same L(y) in Fractions with the costs converted losslessly, so no
    # deflation is needed and the result is checkable by re-running the
    # arithmetic in integers.
    exact = _integer_lagrangian_bound(costs, cuts, dual)
    if exact is None:
        return None
    bound = _fraction_lower_float(exact)
    if bound is None:
        return None
    return max(bound, 0.0)


def _greedy_cover(costs: np.ndarray, cuts: Sequence[np.ndarray]) -> Tuple[int, ...]:
    """Build a cheap feasible master point used only for cut discovery."""

    if not cuts:
        return ()
    cover = np.asarray(cuts, dtype=bool)
    uncovered = np.ones(len(cuts), dtype=bool)
    selected: List[int] = []
    while np.any(uncovered):
        gains = np.count_nonzero(cover[uncovered], axis=0)
        available = np.flatnonzero(gains)
        if not len(available):
            # Deliberately NOT UnresolvedComputation. Unseparable witnesses are
            # detected and returned as UNSYNTHESIZABLE before any cut is
            # inserted, so an all-zero cut reaching the cover builder means the
            # cut set contradicts that check. That is an internal invariant
            # break and must stay loud rather than being reported as an honest
            # "cannot certify".
            raise RuntimeError("registered cuts contain an unseparable witness")
        index = max(
            available,
            key=lambda item: (gains[item] / costs[item], -costs[item], -item),
        )
        selected.append(int(index))
        uncovered &= ~cover[:, index]
    return tuple(sorted(selected))


def _cut_mask(cut: np.ndarray) -> int:
    mask = 0
    for index in np.flatnonzero(cut):
        mask |= 1 << int(index)
    return mask


def _insert_minimal_cut(
    cuts: List[np.ndarray],
    cut: np.ndarray,
    masks: Optional[List[int]] = None,
) -> bool:
    """Maintain the inclusion-minimal antichain of hitting-set constraints."""

    if masks is None:
        masks = [_cut_mask(existing) for existing in cuts]
    mask = _cut_mask(cut)
    if any(existing & mask == existing for existing in masks):
        return False
    keep = [index for index, existing in enumerate(masks) if existing & mask != mask]
    cuts[:] = [cuts[index] for index in keep]
    masks[:] = [masks[index] for index in keep]
    cuts.append(np.asarray(cut, dtype=float))
    masks.append(mask)
    return True


def synthesize_ordered_query(
    candidates: Sequence[CandidateSpace],
    actions: Sequence[MeasurementAction],
    *,
    margin_k: float = 1e-4,
    feasibility_tolerance: float = 1e-10,
    separation_tolerance: float = 1e-9,
    max_iterations: int = 10000,
    separation_workers: Optional[int] = None,
) -> QueryObservationPlan:
    """Exact least-cost plan, decomposed by ordered candidate decisions.

    For two reachable decisions ``i < j``, candidate ``i`` is SAFE on the
    left and REJECT on the right.  Every other unequal state pair contains
    ANY, so the two sides may use the same power vector and no power channel
    can distinguish them.  Candidate-local action libraries therefore make
    the global optimum the sum of the required local SAFE/REJECT optima.
    """

    try:
        if not candidates or not actions:
            raise ContractViolation("ordered candidates and measurement actions are required")
        candidate_map = {candidate.candidate_id: candidate for candidate in candidates}
        if len(candidate_map) != len(candidates):
            raise ContractViolation("candidate IDs must be unique")
        if len({action.action_id for action in actions}) != len(actions):
            raise ContractViolation("measurement action IDs must be unique")
        for action in actions:
            candidate = candidate_map.get(action.candidate_id)
            if candidate is None or action.vector.shape != (candidate.power.dimension,):
                raise ContractViolation("action target or dimension is not registered")
        if margin_k <= 0 or feasibility_tolerance <= 0 or separation_tolerance < 0:
            raise ContractViolation("invalid registered tolerance")
        local_actions = {
            candidate.candidate_id: tuple(
                action
                for action in actions
                if action.candidate_id == candidate.candidate_id
            )
            for candidate in candidates
        }
        required = _required_candidate_indices(
            candidates, margin_k, feasibility_tolerance
        )
        selected_ids: List[str] = []
        lower_bound = relaxation_bound = 0.0
        iterations = 0
        provenances: List[str] = []
        for candidate_index in required:
            candidate = candidates[candidate_index]
            plan = synthesize_minimum_observation(
                candidate.power,
                candidate.thermal,
                local_actions[candidate.candidate_id],
                margin_k=margin_k,
                feasibility_tolerance=feasibility_tolerance,
                separation_tolerance=separation_tolerance,
                max_iterations=max_iterations,
                separation_workers=separation_workers,
            )
            selected_ids.extend(plan.selected_action_ids)
            iterations += plan.iterations
            lower_bound += plan.lower_bound or 0.0
            relaxation_bound += plan.relaxation_bound or 0.0
            if plan.bound_provenance:
                provenances.append(plan.bound_provenance)
            if plan.status != "OPTIMAL":
                witnesses: Tuple[QueryWorldPair, ...] = ()
                if plan.status == "UNSYNTHESIZABLE":
                    witness = _query_collision(
                        candidates,
                        actions,
                        range(len(actions)),
                        margin_k,
                        feasibility_tolerance,
                    )
                    if witness is None:
                        # Also deliberately loud: a candidate-local
                        # UNSYNTHESIZABLE proof that the global oracle cannot
                        # reproduce means the decomposition is unsound, not
                        # that this instance is merely hard.
                        raise RuntimeError(
                            "local and global unsynthesizability certificates disagree"
                        )
                    witnesses = (witness,)
                # Only certified prefixes belong in selected_ids. The failing
                # candidate contributes its working cover as a CANDIDATE, never
                # as part of a certified plan -- this path previously appended
                # the failing local plan's (empty) selected_action_ids and
                # summed its uncomputed lower_bound of 0.0 into the query bound.
                # selected_action_ids must mean "certified for the WHOLE
                # query". A prefix of individually-certified candidates is not
                # that, so it moves to its own field rather than masquerading
                # as a plan.
                #
                # Local bounds ARE summed, correcting an earlier over-caution
                # that returned None here. Theorem 2 gives
                # C*_query = sum over required candidates of C*_i, and action
                # libraries are candidate-local and disjoint, so there is no
                # double counting. Bounds are non-negative, so summing only the
                # candidates reached before the failure still yields a valid --
                # merely weaker -- query lower bound. Dropping it meant every
                # timed-out dev query reported no bound at all, which is
                # precisely the evidence the anytime path exists to produce.
                # `lower_bound` ALREADY includes this candidate's bound: it is
                # accumulated above before the status is examined. Adding it
                # again here double-counted the failing candidate and could push
                # the reported bound ABOVE the true optimum -- an invalid lower
                # bound, which is the one error class this contract exists to
                # exclude. Caught in audit before any result depended on it.
                partial_bound = lower_bound
                return QueryObservationPlan(
                    status=plan.status,
                    selected_action_ids=(),
                    exact_cost=None,
                    lower_bound=partial_bound if partial_bound > 0 else None,
                    relaxation_bound=(
                        relaxation_bound if relaxation_bound > 0 else None
                    ),
                    optimality_gap=None,
                    iterations=iterations,
                    witnesses=witnesses,
                    message=(
                        f"candidate-local decomposition: {plan.message}; "
                        f"certified prefix={len(selected_ids)} actions, "
                        f"failing candidate carries "
                        f"{len(plan.candidate_action_ids)} uncertified candidate actions"
                    ),
                    certified_prefix_action_ids=tuple(selected_ids),
                    bound_provenance=(
                        "solver_branch_and_bound"
                        if any(p == "solver_branch_and_bound" for p in provenances)
                        else "weak_duality"
                        if partial_bound > 0
                        else None
                    ),
                )
        selected_set = set(selected_ids)
        exact_cost = sum(
            action.cost for action in actions if action.action_id in selected_set
        )
        return QueryObservationPlan(
            "OPTIMAL",
            tuple(selected_ids),
            exact_cost,
            lower_bound,
            relaxation_bound,
            exact_cost - lower_bound,
            iterations,
            (),
            "ordered-decision decomposition proves the global batch optimum",
            (),
            # The whole query is self-verifiable only if EVERY candidate was.
            "weak_duality"
            if provenances and all(p == "weak_duality" for p in provenances)
            else "solver_branch_and_bound",
        )
    except _UNRESOLVED_FAILURES as exc:
        return QueryObservationPlan(
            "UNRESOLVED", (), None, None, None, None, 0, (), str(exc)
        )


def synthesize_minimum_observation(
    polytope: PowerPolytope,
    thermal: ThermalFamily,
    actions: Sequence[MeasurementAction],
    *,
    margin_k: float = 1e-4,
    feasibility_tolerance: float = 1e-10,
    separation_tolerance: float = 1e-9,
    max_iterations: int = 10000,
    separation_workers: Optional[int] = None,
    bound_interval: Optional[int] = None,
) -> ObservationPlan:
    """Synthesize the exact minimum-cost non-adaptive observation plan.

    By default the anytime LP lower bound is refreshed at geometric checkpoints
    1, 2, 4, 8, ... during cut discovery. This retains recent proof progress
    with only logarithmically many extra solves. A positive `bound_interval`
    requests a fixed cadence; 0 disables periodic refresh. The bound is also
    attempted once at normal exit.
    """

    # Hoisted above the try so a failure at iteration N still reports the work
    # already done. The handler previously returned iterations=0 with empty
    # witnesses, discarding every discovered cut and witness on any numerical
    # error -- an evidence-destroying failure mode in a project that
    # deliberately retains negative results.
    # Declared, not populated, above the try: building `costs` can itself raise
    # on a malformed action collection, and that must still be converted to
    # UNRESOLVED rather than escaping the documented three-status API.
    costs: Optional[np.ndarray] = None
    cuts: List[np.ndarray] = []
    witnesses: List[WorldPair] = []
    selected: Tuple[int, ...] = ()
    covered_cut_count = 0
    reached = 0
    anytime_bound: Optional[float] = None
    bound_cut_count = 0

    def _refresh_bound() -> None:
        """Keep the best certified bound seen; never lower it.

        Deliberately does NOT catch broadly: `_anytime_lower_bound` already
        converts expected solver/data failures into None, so anything escaping
        it is a programming error and must not be swallowed into a silently
        missing bound.
        """
        nonlocal anytime_bound, bound_cut_count
        if costs is None:
            return
        value = _anytime_lower_bound(costs, cuts)
        if value is not None and (anytime_bound is None or value > anytime_bound):
            anytime_bound = value
            bound_cut_count = len(cuts)

    def _candidate_fields() -> Tuple[Tuple[str, ...], Optional[float]]:  # noqa: D401
        """The last successfully computed working cover. NOT oracle-certified.

        It hits every cut that existed when it was last recomputed -- which on
        an exceptional path may be fewer than the cuts now in `cuts`, if the
        failure happened after insertion but before the cover was rebuilt.
        `covered_cut_count` records which generation it corresponds to.

        Must never raise: it runs inside the exception handler, where throwing
        would mask the original error.
        """
        try:
            if not selected or costs is None:
                return (), None
            return (
                tuple(actions[i].action_id for i in selected),
                float(costs[list(selected)].sum()),
            )
        except Exception:  # pragma: no cover - defensive, must not mask errors
            return (), None

    try:
        if thermal.blocks != polytope.dimension:
            raise ContractViolation("thermal and power dimensions differ")
        if not actions:
            raise ContractViolation("at least one measurement action is required")
        if any(action.vector.shape != (polytope.dimension,) for action in actions):
            raise ContractViolation("every measurement action must match the power dimension")
        if len({action.action_id for action in actions}) != len(actions):
            raise ContractViolation("measurement action IDs must be unique")
        if margin_k <= 0 or feasibility_tolerance <= 0 or separation_tolerance < 0:
            raise ContractViolation("invalid registered tolerance")
        if bound_interval is not None and bound_interval < 0:
            raise ContractViolation("bound_interval must be nonnegative")

        costs = np.asarray([action.cost for action in actions])
        cut_masks: List[int] = []
        master = _solve_master(costs, cuts)
        exact_candidate = False
        for iteration in range(1, max_iterations + 1):
            reached = iteration
            batch = _collisions(
                polytope,
                thermal,
                actions,
                selected,
                margin_k,
                feasibility_tolerance,
                separation_workers,
            )
            if not batch:
                if not exact_candidate:
                    master = _solve_master(costs, cuts, incumbent=selected)
                    if master.selected != selected:
                        selected = master.selected
                        exact_candidate = True
                        continue
                gap = master.cost - master.lower_bound
                return ObservationPlan(
                    status="OPTIMAL",
                    selected_action_ids=tuple(actions[i].action_id for i in master.selected),
                    exact_cost=master.cost,
                    lower_bound=master.lower_bound,
                    relaxation_bound=master.relaxation_bound,
                    optimality_gap=gap,
                    iterations=iteration,
                    witnesses=tuple(witnesses),
                    message=(
                        "zero-error decision uncertainty is eliminated"
                        + (
                            ""
                            if master.bound_provenance == "weak_duality"
                            else "; optimality closed by the solver's asserted "
                            "dual bound, not by a self-contained certificate"
                        )
                    ),
                    bound_provenance=master.bound_provenance,
                )
            added = 0
            for witness in batch:
                delta = witness.safe_power_w - witness.unsafe_power_w
                cut = np.asarray(
                    [
                        abs(float(action.vector @ delta))
                        > action.tolerance + separation_tolerance
                        for action in actions
                    ],
                    dtype=float,
                )
                if not np.any(cut):
                    witnesses.append(witness)
                    candidate_ids, candidate_cost = _candidate_fields()
                    return ObservationPlan(
                        status="UNSYNTHESIZABLE",
                        selected_action_ids=(),
                        exact_cost=None,
                        # Cost optimality is NOT_APPLICABLE here: no plan can
                        # exist, so a bound on the cost of the best plan is
                        # meaningless. Reporting the stale empty-cut master's
                        # 0.0 implied a computed bound that was never computed.
                        lower_bound=None,
                        relaxation_bound=None,
                        optimality_gap=None,
                        iterations=iteration,
                        witnesses=tuple(witnesses),
                        message=f"full action library cannot separate {witness.cause}",
                        candidate_action_ids=candidate_ids,
                        candidate_cost=candidate_cost,
                    )
                if _insert_minimal_cut(cuts, cut, cut_masks):
                    witnesses.append(witness)
                    added += 1
            if not added:
                raise UnresolvedComputation(
                    "collision separation produced no new master cut: the queried "
                    "selection covers every stored cut yet the oracle still "
                    "collides, which indicates a tolerance inconsistency rather "
                    "than ordinary non-convergence"
                )
            selected = _greedy_cover(costs, cuts)
            covered_cut_count = len(cuts)
            exact_candidate = False
            refresh_due = (
                iteration & (iteration - 1) == 0
                if bound_interval is None
                else bool(bound_interval and iteration % bound_interval == 0)
            )
            if refresh_due:
                _refresh_bound()
        _refresh_bound()

        # The loop tests `selected` at the TOP of each iteration, so the cover
        # produced by the final iteration's greedy rebuild has never been shown
        # to the oracle. One more separation pass costs a single batch and can
        # promote it from an uncertified candidate to a CERTIFIED plan -- which
        # is what turns its cost into a genuine upper bound and makes an
        # anytime gap meaningful at all. Without this a run could hold a
        # provably collision-free plan and still report nothing usable.
        final_batch = _collisions(
            polytope,
            thermal,
            actions,
            selected,
            margin_k,
            feasibility_tolerance,
            separation_workers,
        )
        if not final_batch:
            # `selected` may legitimately be EMPTY: if the decision is already
            # invariant over every admissible world, the zero-cost contract is
            # a valid certified plan. Requiring a nonempty plan here would have
            # reported that case as UNRESOLVED.
            certified_ids = tuple(actions[i].action_id for i in selected)
            certified_cost = (
                float(costs[list(selected)].sum()) if selected else 0.0
            )
            gap = None
            if anytime_bound is not None:
                raw = certified_cost - anytime_bound
                if raw < -1e-6 * max(1.0, certified_cost):
                    # A certified plan cheaper than a certified lower bound is
                    # an invariant violation, not a small numerical artifact.
                    raise UnresolvedComputation(
                        f"certified plan cost {certified_cost} lies below the "
                        f"certified lower bound {anytime_bound}"
                    )
                gap = max(0.0, raw)
            return ObservationPlan(
                status="CERTIFIED_PLAN",
                # Oracle-certified: no admissible pair of worlds with different
                # decisions survives these observations. NOT proven cheapest.
                # Built directly from `selected` -- the exact set handed to the
                # oracle -- so the reported certificate cannot drift from what
                # was actually checked.
                selected_action_ids=certified_ids,
                exact_cost=None,
                lower_bound=anytime_bound,
                relaxation_bound=anytime_bound,
                upper_bound=certified_cost,
                # A REAL certified interval width: a feasible plan's cost minus
                # a valid lower bound. Distinct from candidate_cost - bound,
                # which bounds nothing because an uncertified cover need not be
                # feasible. Exact rational evaluation plus downward conversion
                # may leave only the representational slack of the output
                # float; it can never make the reported lower endpoint larger.
                optimality_gap=gap,
                iterations=max_iterations,
                witnesses=tuple(witnesses),
                message=(
                    "decision-identifying observation contract certified by an "
                    "exhaustive final separation pass; minimum cost not proven "
                    "within the registered constraint-generation budget"
                ),
                candidate_action_ids=(),
                candidate_cost=None,
                bound_provenance=(
                    "weak_duality" if anytime_bound is not None else None
                ),
            )
        # The final pass found fresh collisions. They are the newest and most
        # relevant counterexamples, so they belong in the returned evidence
        # even though the budget prevents another rebuild.
        witnesses.extend(final_batch)
        candidate_ids, candidate_cost = _candidate_fields()
        return ObservationPlan(
            status="UNRESOLVED",
            # Nothing was certified: the loop only proves a plan collision-free
            # on the `not batch` branch, which budget exhaustion never reached.
            # This field previously reported `master.selected`, which on this
            # path is still the empty-cut master from initialisation -- so a run
            # holding an 11-action working cover reported zero actions and a
            # lower_bound of 0.0 that was never computed from any cut.
            selected_action_ids=(),
            exact_cost=None,
            # A certified global lower bound from the discovered cuts (see
            # `_anytime_lower_bound`), replacing the stale 0.0.
            # NOTE: candidate_cost - lower_bound is NOT an optimality gap and
            # NOT an overspending bound. candidate_cost is not a valid upper
            # bound -- the cover is feasible for the restricted master only, so
            # it may even be CHEAPER than every globally feasible plan. The
            # difference bounds nothing about the true optimum.
            lower_bound=anytime_bound,
            relaxation_bound=anytime_bound,
            optimality_gap=None,
            iterations=max_iterations,
            witnesses=tuple(witnesses),
            message="registered constraint-generation budget exhausted",
            candidate_action_ids=candidate_ids,
            candidate_cost=candidate_cost,
            candidate_covered_cuts=covered_cut_count,
            bound_provenance=(
                "weak_duality" if anytime_bound is not None else None
            ),
        )
    except _UNRESOLVED_FAILURES as exc:
        if isinstance(exc, TimeoutError):
            # A timer interrupt fires BETWEEN operations, so unlike a numerical
            # failure the cut set is intact and a bound computed from it is
            # valid. Refreshing here is what lets a budget-exhausted run report
            # an actual interval instead of an empty bound column -- the whole
            # value of the anytime path. Guarded so a failure here cannot mask
            # the timeout itself.
            try:
                _refresh_bound()
            except _UNRESOLVED_FAILURES:
                pass
        candidate_ids, candidate_cost = _candidate_fields()
        return ObservationPlan(
            status="UNRESOLVED",
            selected_action_ids=(),
            exact_cost=None,
            # For a numerical failure the state that raised may be inconsistent,
            # so whatever bound the cuts had already established is reported
            # unchanged; for a timeout it has just been refreshed above.
            lower_bound=anytime_bound,
            relaxation_bound=anytime_bound,
            optimality_gap=None,
            iterations=reached,
            witnesses=tuple(witnesses),
            message=str(exc),
            candidate_action_ids=candidate_ids,
            candidate_cost=candidate_cost,
            # How many cuts this cover actually hits. On an interrupted run it
            # can be fewer than len(cuts): the failure may land after a cut is
            # inserted but before the cover is rebuilt.
            candidate_covered_cuts=covered_cut_count,
            bound_provenance=(
                "weak_duality" if anytime_bound is not None else None
            ),
        )
