"""Exact zero-error decision observation synthesis by constraint generation.

The finite master is a minimum-cost hitting-set MILP.  Its constraints are
generated by a continuous LP oracle that searches for two admissible power
worlds with different thermal decisions but identical selected observations.
When the oracle finds no collision, the master lower bound and feasible plan
meet: the returned batch plan is globally minimum-cost for the registered
action library, model family, margins, and numerical tolerances.
"""

from __future__ import annotations

from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass
import os
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

import numpy as np
from scipy.optimize import Bounds, LinearConstraint, linprog, milp

from .core import (
    CandidateSpace,
    CandidateWorldPair,
    MeasurementAction,
    ObservationPlan,
    PowerPolytope,
    QueryObservationPlan,
    QueryWorldPair,
    ThermalFamily,
    WorldPair,
)


@dataclass(frozen=True)
class _Master:
    selected: Tuple[int, ...]
    cost: float
    lower_bound: float
    relaxation_bound: float
    dual_prices: np.ndarray


def _configured_workers(workers: Optional[int] = None) -> int:
    value = workers
    if value is None:
        value = int(os.environ.get("CERTITHERM_LP_WORKERS", "8"))
    if value <= 0:
        raise ValueError("LP separation workers must be positive")
    return value


def _pair_rows(polytope: PowerPolytope) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    n = polytope.dimension
    zeros_eq = np.zeros((polytope.a_eq.shape[0], n))
    a_eq = np.vstack(
        (np.hstack((polytope.a_eq, zeros_eq)), np.hstack((zeros_eq, polytope.a_eq)))
    )
    b_eq = np.concatenate((polytope.b_eq, polytope.b_eq))
    zeros_ub = np.zeros((polytope.a_ub.shape[0], n))
    a_ub = np.vstack(
        (np.hstack((polytope.a_ub, zeros_ub)), np.hstack((zeros_ub, polytope.a_ub)))
    )
    b_ub = np.concatenate((polytope.b_ub, polytope.b_ub))
    return a_eq, b_eq, a_ub, b_ub


def _robust_safe_rows(
    thermal: ThermalFamily, margin_k: float
) -> Tuple[np.ndarray, np.ndarray]:
    """All model/point upper bounds defining one fail-closed SAFE cell."""

    rows = thermal.response_k_per_w.reshape(-1, thermal.blocks)
    rhs = (
        thermal.limit_k
        - margin_k
        - thermal.error_k[:, None]
        - thermal.ambient_k
    ).reshape(-1)
    return rows, rhs


def _collision_search(
    polytope: PowerPolytope,
    thermal: ThermalFamily,
    actions: Sequence[MeasurementAction],
    selected: Iterable[int],
    margin_k: float,
    feasibility_tolerance: float,
    workers: Optional[int],
    exhaustive: bool,
) -> Tuple[WorldPair, ...]:
    """Separate safe/reject cells with deterministic parallel LP batches."""

    n = polytope.dimension
    a_eq, b_eq, base_a_ub, base_b_ub = _pair_rows(polytope)
    action_rows: List[np.ndarray] = []
    action_rhs: List[float] = []
    for index in selected:
        action = actions[index]
        delta = np.concatenate((action.vector, -action.vector))
        action_rows.extend((delta, -delta))
        action_rhs.extend((action.tolerance, action.tolerance))

    bounds = list(zip(polytope.lower_w, polytope.upper_w)) * 2
    response = thermal.response_k_per_w
    ambient = thermal.ambient_k
    robust_rows, robust_rhs = _robust_safe_rows(thermal, margin_k)
    safe_rows = np.hstack((robust_rows, np.zeros_like(robust_rows)))
    common_chunks = [base_a_ub, safe_rows]
    common_rhs_chunks = [base_b_ub, robust_rhs]
    if action_rows:
        common_chunks.append(np.asarray(action_rows))
        common_rhs_chunks.append(np.asarray(action_rhs))
    common_a_ub = np.vstack(common_chunks)
    common_b_ub = np.concatenate(common_rhs_chunks)
    specs = tuple(
        (reject_model, point)
        for reject_model in range(response.shape[0])
        for point in range(response.shape[1])
    )
    worker_count = min(_configured_workers(workers), len(specs))

    def solve(spec: Tuple[int, int]) -> Optional[WorldPair]:
        reject_model, point = spec
        reject_row = np.concatenate((np.zeros(n), -response[reject_model, point]))
        reject_rhs = -(
            thermal.limit_k
            + margin_k
            - thermal.error_k[reject_model]
            - ambient[reject_model, point]
        )
        result = linprog(
            np.zeros(2 * n),
            A_ub=np.vstack((common_a_ub, reject_row)),
            b_ub=np.append(common_b_ub, reject_rhs),
            A_eq=a_eq,
            b_eq=b_eq,
            bounds=bounds,
            method="highs",
            options={
                "primal_feasibility_tolerance": feasibility_tolerance,
                "dual_feasibility_tolerance": feasibility_tolerance,
            },
        )
        if result.status == 0:
            return WorldPair(
                safe_power_w=result.x[:n].copy(),
                unsafe_power_w=result.x[n:].copy(),
                safe_model_id="ROBUST_ENVELOPE",
                unsafe_model_id=thermal.model_ids[reject_model],
                unsafe_point=point,
            )
        if result.status != 2:
            raise RuntimeError(f"collision LP unresolved: {result.message}")
        return None

    if worker_count == 1:
        collisions = []
        for spec in specs:
            collision = solve(spec)
            if collision is not None:
                collisions.append(collision)
                if not exhaustive:
                    break
        return tuple(collisions)

    collisions: List[WorldPair] = []
    with ThreadPoolExecutor(max_workers=worker_count) as pool:
        if exhaustive:
            return tuple(
                collision
                for collision in pool.map(solve, specs)
                if collision is not None
            )
        for start in range(0, len(specs), worker_count):
            batch = tuple(pool.map(solve, specs[start : start + worker_count]))
            collision = next((item for item in batch if item is not None), None)
            if collision is not None:
                collisions.append(collision)
                break
    return tuple(collisions)


def _collision(
    polytope: PowerPolytope,
    thermal: ThermalFamily,
    actions: Sequence[MeasurementAction],
    selected: Iterable[int],
    margin_k: float,
    feasibility_tolerance: float,
    workers: Optional[int] = None,
) -> Optional[WorldPair]:
    """Return the first collision; certify absence by parallel exhaustive scan."""

    collisions = _collision_search(
        polytope,
        thermal,
        actions,
        selected,
        margin_k,
        feasibility_tolerance,
        workers,
        False,
    )
    return collisions[0] if collisions else None


def _collisions(
    polytope: PowerPolytope,
    thermal: ThermalFamily,
    actions: Sequence[MeasurementAction],
    selected: Iterable[int],
    margin_k: float,
    feasibility_tolerance: float,
    workers: Optional[int] = None,
) -> Tuple[WorldPair, ...]:
    """Return one collision per reachable reject cell in deterministic order."""

    return _collision_search(
        polytope,
        thermal,
        actions,
        selected,
        margin_k,
        feasibility_tolerance,
        workers,
        True,
    )


def _state_specs(thermal: ThermalFamily, state: str) -> Iterable[Tuple[int, int]]:
    if state == "ANY":
        return ((-1, -1),)
    if state == "SAFE":
        return ((-1, -1),)
    if state == "REJECT":
        return (
            (model, point)
            for model in range(len(thermal.model_ids))
            for point in range(thermal.response_k_per_w.shape[1])
        )
    raise ValueError(f"unknown decision state {state}")


def _state_constraints(
    thermal: ThermalFamily,
    state: str,
    model: int,
    point: int,
    side: int,
    margin_k: float,
) -> Tuple[np.ndarray, np.ndarray]:
    n = thermal.blocks
    if state == "ANY":
        return np.empty((0, 2 * n)), np.empty(0)
    if state == "SAFE":
        rows, rhs = _robust_safe_rows(thermal, margin_k)
    else:
        response = thermal.response_k_per_w[model]
        rows = -response[point][None, :]
        rhs = np.array(
            [
                -(
                    thermal.limit_k
                    + margin_k
                    - thermal.error_k[model]
                    - thermal.ambient_k[model, point]
                )
            ]
        )
    pad = np.zeros_like(rows)
    return (np.hstack((rows, pad)) if side == 0 else np.hstack((pad, rows))), rhs


def _single_state_world(
    candidate: CandidateSpace,
    state: str,
    margin_k: float,
    feasibility_tolerance: float,
) -> Optional[Tuple[np.ndarray, str]]:
    """Find one world in a state; used to couple equal-state query sides."""

    power, thermal = candidate.power, candidate.thermal
    for model, point in _state_specs(thermal, state):
        if state == "ANY":
            rows, rhs, model_id = power.a_ub, power.b_ub, "UNCONSTRAINED"
        elif state == "SAFE":
            safe_rows, safe_rhs = _robust_safe_rows(thermal, margin_k)
            rows = np.vstack((power.a_ub, safe_rows))
            rhs = np.concatenate(
                (
                    power.b_ub,
                    safe_rhs,
                )
            )
            model_id = "ROBUST_ENVELOPE"
        else:
            rows = np.vstack(
                (power.a_ub, -thermal.response_k_per_w[model, point][None, :])
            )
            rhs = np.concatenate(
                (
                    power.b_ub,
                    np.array(
                        [
                            -(
                                thermal.limit_k
                                + margin_k
                                - thermal.error_k[model]
                                - thermal.ambient_k[model, point]
                            )
                        ]
                    ),
                )
            )
            model_id = thermal.model_ids[model]
        result = linprog(
            np.zeros(power.dimension),
            A_ub=rows,
            b_ub=rhs,
            A_eq=power.a_eq,
            b_eq=power.b_eq,
            bounds=list(zip(power.lower_w, power.upper_w)),
            method="highs",
            options={
                "primal_feasibility_tolerance": feasibility_tolerance,
                "dual_feasibility_tolerance": feasibility_tolerance,
            },
        )
        if result.status == 0:
            return result.x.copy(), model_id
        if result.status != 2:
            raise RuntimeError(f"state feasibility LP unresolved: {result.message}")
    return None


def _state_model_id(thermal: ThermalFamily, state: str, model: int) -> str:
    if state == "SAFE":
        return "ROBUST_ENVELOPE"
    if state == "ANY":
        return "UNCONSTRAINED"
    return thermal.model_ids[model]


def _state_collision(
    candidate: CandidateSpace,
    actions: Sequence[MeasurementAction],
    selected: Iterable[int],
    left_state: str,
    right_state: str,
    margin_k: float,
    feasibility_tolerance: float,
) -> Optional[CandidateWorldPair]:
    polytope, thermal = candidate.power, candidate.thermal
    if left_state == right_state:
        world = _single_state_world(
            candidate, left_state, margin_k, feasibility_tolerance
        )
        if world is None:
            return None
        power, model_id = world
        return CandidateWorldPair(
            candidate_id=candidate.candidate_id,
            left_power_w=power,
            right_power_w=power.copy(),
            left_state=left_state,
            right_state=right_state,
            left_model_id=model_id,
            right_model_id=model_id,
        )
    n = polytope.dimension
    a_eq, b_eq, base_a_ub, base_b_ub = _pair_rows(polytope)
    action_rows, action_rhs = [], []
    for index in selected:
        action = actions[index]
        delta = np.concatenate((action.vector, -action.vector))
        action_rows.extend((delta, -delta))
        action_rhs.extend((action.tolerance, action.tolerance))
    bounds = list(zip(polytope.lower_w, polytope.upper_w)) * 2
    for left_model, left_point in _state_specs(thermal, left_state):
        left_rows, left_rhs = _state_constraints(
            thermal, left_state, left_model, left_point, 0, margin_k
        )
        for right_model, right_point in _state_specs(thermal, right_state):
            right_rows, right_rhs = _state_constraints(
                thermal, right_state, right_model, right_point, 1, margin_k
            )
            chunks = [base_a_ub, left_rows, right_rows]
            rhs_chunks = [base_b_ub, left_rhs, right_rhs]
            if action_rows:
                chunks.append(np.asarray(action_rows))
                rhs_chunks.append(np.asarray(action_rhs))
            result = linprog(
                np.zeros(2 * n),
                A_ub=np.vstack(chunks),
                b_ub=np.concatenate(rhs_chunks),
                A_eq=a_eq,
                b_eq=b_eq,
                bounds=bounds,
                method="highs",
                options={
                    "primal_feasibility_tolerance": feasibility_tolerance,
                    "dual_feasibility_tolerance": feasibility_tolerance,
                },
            )
            if result.status == 0:
                return CandidateWorldPair(
                    candidate_id=candidate.candidate_id,
                    left_power_w=result.x[:n].copy(),
                    right_power_w=result.x[n:].copy(),
                    left_state=left_state,
                    right_state=right_state,
                    left_model_id=_state_model_id(
                        thermal, left_state, left_model
                    ),
                    right_model_id=_state_model_id(
                        thermal, right_state, right_model
                    ),
                )
            if result.status != 2:
                raise RuntimeError(f"query collision LP unresolved: {result.message}")
    return None


def _decision_states(candidate_count: int, decision: int) -> Tuple[str, ...]:
    if decision == candidate_count:
        return ("REJECT",) * candidate_count
    return tuple(
        "REJECT" if index < decision else "SAFE" if index == decision else "ANY"
        for index in range(candidate_count)
    )


def _required_candidate_indices(
    candidates: Sequence[CandidateSpace],
    margin_k: float,
    feasibility_tolerance: float,
) -> Tuple[int, ...]:
    """Candidates whose SAFE/REJECT ambiguity changes a reachable decision."""

    state_exists = {
        (index, state): _single_state_world(
            candidate, state, margin_k, feasibility_tolerance
        )
        is not None
        for index, candidate in enumerate(candidates)
        for state in ("ANY", "SAFE", "REJECT")
    }
    reachable = tuple(
        decision
        for decision in range(len(candidates) + 1)
        if all(
            state_exists[index, state]
            for index, state in enumerate(
                _decision_states(len(candidates), decision)
            )
        )
    )
    return tuple(
        decision
        for decision in reachable[:-1]
        if decision < len(candidates)
    )


def _query_collision(
    candidates: Sequence[CandidateSpace],
    actions: Sequence[MeasurementAction],
    selected: Iterable[int],
    margin_k: float,
    feasibility_tolerance: float,
    cache: Optional[
        Dict[Tuple[int, Tuple[int, ...], str, str], Optional[CandidateWorldPair]]
    ] = None,
) -> Optional[QueryWorldPair]:
    selected_set = set(selected)
    action_index = {
        candidate.candidate_id: [
            index for index, action in enumerate(actions) if action.candidate_id == candidate.candidate_id
        ]
        for candidate in candidates
    }
    for left_decision in range(len(candidates) + 1):
        left_states = _decision_states(len(candidates), left_decision)
        for right_decision in range(left_decision + 1, len(candidates) + 1):
            right_states = _decision_states(len(candidates), right_decision)
            pairs = []
            for candidate_index, (candidate, left_state, right_state) in enumerate(
                zip(candidates, left_states, right_states)
            ):
                global_indices = action_index[candidate.candidate_id]
                local_actions = [actions[index] for index in global_indices]
                local_selected = [
                    local for local, index in enumerate(global_indices) if index in selected_set
                ]
                key = (
                    candidate_index,
                    tuple(local_selected),
                    left_state,
                    right_state,
                )
                if cache is not None and key in cache:
                    pair = cache[key]
                else:
                    pair = _state_collision(
                        candidate,
                        local_actions,
                        local_selected,
                        left_state,
                        right_state,
                        margin_k,
                        feasibility_tolerance,
                    )
                    if cache is not None:
                        cache[key] = pair
                if pair is None:
                    break
                pairs.append(pair)
            if len(pairs) == len(candidates):
                name = lambda value: (
                    candidates[value].candidate_id
                    if value < len(candidates)
                    else "NO_FEASIBLE_CANDIDATE"
                )
                return QueryWorldPair(
                    left_decision=name(left_decision),
                    right_decision=name(right_decision),
                    candidates=tuple(pairs),
                )
    return None


def _solve_master(costs: np.ndarray, cuts: Sequence[np.ndarray]) -> _Master:
    if not cuts:
        return _Master((), 0.0, 0.0, 0.0, np.empty(0))
    cover = np.asarray(cuts, dtype=float)
    constraint = LinearConstraint(cover, np.ones(len(cuts)), np.full(len(cuts), np.inf))
    integer = milp(
        c=costs,
        integrality=np.ones(costs.size),
        bounds=Bounds(np.zeros(costs.size), np.ones(costs.size)),
        constraints=constraint,
        options={"mip_rel_gap": 0.0},
    )
    relaxed = linprog(
        costs,
        A_ub=-cover,
        b_ub=-np.ones(len(cuts)),
        bounds=[(0.0, 1.0)] * costs.size,
        method="highs",
    )
    if not integer.success or not relaxed.success:
        raise RuntimeError("observation master did not solve to optimality")
    selected = tuple(np.flatnonzero(integer.x > 0.5).tolist())
    dual = -np.asarray(relaxed.ineqlin.marginals)
    lower_bound = float(getattr(integer, "mip_dual_bound", integer.fun))
    return _Master(selected, float(integer.fun), lower_bound, float(relaxed.fun), dual)


def dual_information_scores(
    actions: Sequence[MeasurementAction],
    cuts: Sequence[np.ndarray],
    dual_prices: np.ndarray,
) -> np.ndarray:
    """Zero-error InfoCertGain/cost induced by the master LP dual."""

    if not cuts:
        return np.zeros(len(actions))
    cover = np.asarray(cuts, dtype=float)
    costs = np.asarray([action.cost for action in actions])
    return cover.T @ np.asarray(dual_prices) / costs


def synthesize_ordered_query(
    candidates: Sequence[CandidateSpace],
    actions: Sequence[MeasurementAction],
    *,
    margin_k: float = 1e-4,
    feasibility_tolerance: float = 1e-10,
    separation_tolerance: float = 1e-9,
    max_iterations: int = 10000,
    separation_workers: Optional[int] = None,
) -> QueryObservationPlan:
    """Exact least-cost plan, decomposed by ordered candidate decisions.

    For two reachable decisions ``i < j``, candidate ``i`` is SAFE on the
    left and REJECT on the right.  Every other unequal state pair contains
    ANY, so the two sides may use the same power vector and no power channel
    can distinguish them.  Candidate-local action libraries therefore make
    the global optimum the sum of the required local SAFE/REJECT optima.
    """

    try:
        if not candidates or not actions:
            raise ValueError("ordered candidates and measurement actions are required")
        candidate_map = {candidate.candidate_id: candidate for candidate in candidates}
        if len(candidate_map) != len(candidates):
            raise ValueError("candidate IDs must be unique")
        if len({action.action_id for action in actions}) != len(actions):
            raise ValueError("measurement action IDs must be unique")
        for action in actions:
            candidate = candidate_map.get(action.candidate_id)
            if candidate is None or action.vector.shape != (candidate.power.dimension,):
                raise ValueError("action target or dimension is not registered")
        if margin_k <= 0 or feasibility_tolerance <= 0 or separation_tolerance < 0:
            raise ValueError("invalid registered tolerance")
        local_actions = {
            candidate.candidate_id: tuple(
                action
                for action in actions
                if action.candidate_id == candidate.candidate_id
            )
            for candidate in candidates
        }
        required = _required_candidate_indices(
            candidates, margin_k, feasibility_tolerance
        )
        selected_ids: List[str] = []
        lower_bound = relaxation_bound = 0.0
        iterations = 0
        for candidate_index in required:
            candidate = candidates[candidate_index]
            plan = synthesize_minimum_observation(
                candidate.power,
                candidate.thermal,
                local_actions[candidate.candidate_id],
                margin_k=margin_k,
                feasibility_tolerance=feasibility_tolerance,
                separation_tolerance=separation_tolerance,
                max_iterations=max_iterations,
                separation_workers=separation_workers,
            )
            selected_ids.extend(plan.selected_action_ids)
            iterations += plan.iterations
            lower_bound += plan.lower_bound or 0.0
            relaxation_bound += plan.relaxation_bound or 0.0
            if plan.status != "OPTIMAL":
                witnesses: Tuple[QueryWorldPair, ...] = ()
                if plan.status == "UNSYNTHESIZABLE":
                    witness = _query_collision(
                        candidates,
                        actions,
                        range(len(actions)),
                        margin_k,
                        feasibility_tolerance,
                    )
                    if witness is None:
                        raise RuntimeError(
                            "local and global unsynthesizability certificates disagree"
                        )
                    witnesses = (witness,)
                return QueryObservationPlan(
                    plan.status,
                    tuple(selected_ids),
                    None,
                    lower_bound,
                    relaxation_bound,
                    None,
                    iterations,
                    witnesses,
                    f"candidate-local decomposition: {plan.message}",
                )
        selected_set = set(selected_ids)
        exact_cost = sum(
            action.cost for action in actions if action.action_id in selected_set
        )
        return QueryObservationPlan(
            "OPTIMAL",
            tuple(selected_ids),
            exact_cost,
            lower_bound,
            relaxation_bound,
            exact_cost - lower_bound,
            iterations,
            (),
            "ordered-decision decomposition proves the global batch optimum",
        )
    except (ValueError, RuntimeError) as exc:
        return QueryObservationPlan(
            "UNRESOLVED", (), None, None, None, None, 0, (), str(exc)
        )


def synthesize_minimum_observation(
    polytope: PowerPolytope,
    thermal: ThermalFamily,
    actions: Sequence[MeasurementAction],
    *,
    margin_k: float = 1e-4,
    feasibility_tolerance: float = 1e-10,
    separation_tolerance: float = 1e-9,
    max_iterations: int = 10000,
    separation_workers: Optional[int] = None,
) -> ObservationPlan:
    """Synthesize the exact minimum-cost non-adaptive observation plan."""

    try:
        if thermal.blocks != polytope.dimension:
            raise ValueError("thermal and power dimensions differ")
        if not actions:
            raise ValueError("at least one measurement action is required")
        if any(action.vector.shape != (polytope.dimension,) for action in actions):
            raise ValueError("every measurement action must match the power dimension")
        if len({action.action_id for action in actions}) != len(actions):
            raise ValueError("measurement action IDs must be unique")
        if margin_k <= 0 or feasibility_tolerance <= 0 or separation_tolerance < 0:
            raise ValueError("invalid registered tolerance")

        costs = np.asarray([action.cost for action in actions])
        cuts: List[np.ndarray] = []
        witnesses: List[WorldPair] = []
        master = _solve_master(costs, cuts)
        for iteration in range(1, max_iterations + 1):
            batch = _collisions(
                polytope,
                thermal,
                actions,
                master.selected,
                margin_k,
                feasibility_tolerance,
                separation_workers,
            )
            if not batch:
                gap = master.cost - master.lower_bound
                return ObservationPlan(
                    status="OPTIMAL",
                    selected_action_ids=tuple(actions[i].action_id for i in master.selected),
                    exact_cost=master.cost,
                    lower_bound=master.lower_bound,
                    relaxation_bound=master.relaxation_bound,
                    optimality_gap=gap,
                    iterations=iteration,
                    witnesses=tuple(witnesses),
                    message="zero-error decision uncertainty is eliminated",
                )
            known = {np.packbits(cut.astype(np.uint8)).tobytes() for cut in cuts}
            added = 0
            for witness in batch:
                witnesses.append(witness)
                delta = witness.safe_power_w - witness.unsafe_power_w
                cut = np.asarray(
                    [
                        abs(float(action.vector @ delta))
                        > action.tolerance + separation_tolerance
                        for action in actions
                    ],
                    dtype=float,
                )
                if not np.any(cut):
                    return ObservationPlan(
                        status="UNSYNTHESIZABLE",
                        selected_action_ids=tuple(
                            actions[i].action_id for i in master.selected
                        ),
                        exact_cost=None,
                        lower_bound=master.lower_bound,
                        relaxation_bound=master.relaxation_bound,
                        optimality_gap=None,
                        iterations=iteration,
                        witnesses=tuple(witnesses),
                        message=f"full action library cannot separate {witness.cause}",
                    )
                key = np.packbits(cut.astype(np.uint8)).tobytes()
                if key not in known:
                    cuts.append(cut)
                    known.add(key)
                    added += 1
            if not added:
                raise RuntimeError("collision separation produced no new master cut")
            master = _solve_master(costs, cuts)
        return ObservationPlan(
            status="UNRESOLVED",
            selected_action_ids=tuple(actions[i].action_id for i in master.selected),
            exact_cost=None,
            lower_bound=master.lower_bound,
            relaxation_bound=master.relaxation_bound,
            optimality_gap=None,
            iterations=max_iterations,
            witnesses=tuple(witnesses),
            message="registered constraint-generation budget exhausted",
        )
    except (ValueError, RuntimeError) as exc:
        return ObservationPlan(
            status="UNRESOLVED",
            selected_action_ids=(),
            exact_cost=None,
            lower_bound=None,
            relaxation_bound=None,
            optimality_gap=None,
            iterations=0,
            witnesses=(),
            message=str(exc),
        )
